aws:
  key_id:
      keyid
  key:
      key

client_registration_secret:
  naifniwuenfanfiownef

server:
  port: 8084

logging:
  level:
    org:
      springframework:
        security:
          DEBUG

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/provider_service
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      username: grant
      password: grant

keplara:
  client_id: ijcwfsnijf389hs38hs9w38r
  client_secret: fnao309fnwauifh3p9a8h4rksfh03nwfh309   
secretKey: 0DdF4QygeOYsBTzjV2z1jxNz1FZVW3ajTpI1bTui5zY
payloadKey: 0DdF4QygeOYsBTzjV2z1jxNz1FZVW3ajTpI1bTui5zY
service_account_key_file: /key.json
